name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'dist/linux/README-linux.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'dist/linux/README-linux.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check.yml
